### ISSUE TITLE
[Task 2] Create a Template for Documentation and Coding Standards

### ISSUE THREAD

**Issue by VD-25** [VD-25/resume-analyzer#6]
## User story
As a developer, I'd like to create a Template for Documentation and Coding Standards

## Description
Create a Template for Documentation and Coding Standards

## Acceptance Criteria
- [ ] CONTRIBUTING.MD
- [ ] STYLE_GUIDE.MD
- [ ] SETUP.MD

**Comment by truongd3** [comment]
Create a PR @VD-25
