### ISSUE TITLE
[Task 6 + 7] Develop Frontend Components for Registration and Login Forms + Integrate Frontend with Authentication API

### ISSUE THREAD

**Issue by fchen829** [VD-25/resume-analyzer#7]
### Description:
- Build forms in React.
Instructions:
- Create SignUp and Login components.

### Fields:
- Sign Up: Email, Username, Password, Confirm Password.
- Login: Email, Password.
- Use Axios to send data to backend.
Unit Tests: Mock API responses.

**Comment by danhelmer** [comment]
dummy components added and work
separate registration and login pages

need to fix how to form submission info is stored because as of now the login page cannot see registered users because the info is not shared - need to fix
